### ISSUE TITLE
validation for certain documents _always_ fails

### ISSUE THREAD

**Issue by Mtillmann** [sanity-io/webhook-toolkit#39]
The validation for certain documents always fails. I have no Idea what causes the issue but it makes the validation pointless. The documents that it fails on look exactly like documents that pass the validation. Any pointers would be appreciated as I have to disable the validation until this works as expected

**Comment by Mtillmann** [comment]
Thanks for your replies. The issue seems to be related to your other comment and problems with the JSON encode. What would be way to make it work consistently with express?

**Comment by rexxars** [comment]
> What would be way to make it work consistently with express?

There's an example [in the README](https://github.com/sanity-io/webhook-toolkit#usage-with-expressjs-or-similar). You have to make sure the body is not parsed as JSON when you validate the payload. The easiest is to use the `bodyParser.text()` middleware along with `requireSignedRequest()`, which will parse the body to JSON for you if the signature is valid.
